### ISSUE TITLE
post不能缓存?

### ISSUE THREAD

**Issue by pheromone** [ChenYilong/ParseSourceCodeStudy#16]
POST请求不能被缓存，只有 GET 请求能被缓存.   意思是post不能缓存,还是不建议缓存?   那么QQ缓存的聊天数据是get请求下来的?

**Comment by yangxiangnan** [comment]
不建议缓存，qq跟这个无关

**Comment by pheromone** [comment]
意思就是 post get都可以缓存,但是不建议post缓存.

**Comment by ChenYilong** [comment]
都可以缓存。post缓存需要自己实现缓存逻辑。
