### ISSUE TITLE
笔误

### ISSUE THREAD

**Issue by kingstal** [ChenYilong/ParseSourceCodeStudy#2]
串行队列能确保顺序执行任务，他们两个的唯一区别在于`dispatch_sync `只会在 block 完全执行完之后返回，`dispatch_sync `不能确保会在 block 完全执行完之后返回，唯一能确定的是会在被添加到queue 队列后返回。

第二个应该是`dispatch_async `吧

**Comment by ChenYilong** [comment]
非常感谢您的细心， [已经修复](https://github.com/ChenYilong/ParseSourceCodeStudy/commit/8d3841de5fb1e1c46bef6090a8c91bcd069eb864) ，帮忙看下还有什么地方有问题吗？再次感谢
